// Ragdoll Lab design tokens. Single source for the Figma plugin and the local preview.
// Primitives are raw values; semantic colors alias exactly one primitive.

var RDL_PRIMITIVES = {
  'ink/900': '#161A23',
  'ink/800': '#252B3A',
  'slate/50': '#F4F7FA',
  'slate/100': '#E3E9EF',
  'slate/200': '#CBD5DF',
  'slate/300': '#A8B5C3',
  'slate/400': '#7F8FA1',
  'slate/500': '#5D6B7C',
  'slate/600': '#435062',
  'slate/700': '#303A48',
  'white': '#FFFFFF',
  'yellow/300': '#FFE27A',
  'yellow/400': '#FFC93C',
  'yellow/500': '#F2A700',
  'yellow/600': '#C98300',
  'orange/400': '#FF9A3D',
  'orange/500': '#F07300',
  'red/400': '#FF5A52',
  'red/500': '#E5322B',
  'red/600': '#B3201B',
  'pink/500': '#FF2D7A',
  'green/300': '#9BF0BE',
  'green/400': '#45DD86',
  'green/500': '#1DB95F',
  'green/600': '#128A45',
  'blue/300': '#8FCDFF',
  'blue/400': '#4AA8FF',
  'blue/500': '#1E86F0',
  'blue/600': '#1466BD',
  'purple/400': '#B07CFF',
  'purple/500': '#8B4CEF',
};

// [primitive, description]
var RDL_COLORS = {
  'art/outline': ['ink/900', 'Universal 4px outline for every in-world sprite'],

  'room/wall': ['slate/200', 'Back wall base'],
  'room/wall-panel': ['slate/100', 'Inset wall panels'],
  'room/wall-seam': ['slate/300', 'Panel seams, bolts, baseboard'],
  'room/side-wall': ['slate/400', 'Left and right walls'],
  'room/side-wall-shade': ['slate/500', 'Inner edge of side walls'],
  'room/ceiling': ['slate/600', 'Ceiling slab'],
  'room/floor': ['slate/500', 'Floor body'],
  'room/floor-top': ['slate/300', 'Walkable floor lip'],
  'room/floor-shade': ['slate/600', 'Floor plate seams'],
  'room/hazard-a': ['yellow/400', 'Hazard stripe light'],
  'room/hazard-b': ['ink/800', 'Hazard stripe dark'],
  'room/glass': ['blue/300', 'Observation window glass'],
  'room/light': ['white', 'Lamps, light cones, glass shine'],
  'room/grid': ['blue/400', 'Placement snap grid'],
  'room/shadow': ['ink/900', 'Contact shadows (use with opacity)'],

  'subject/body': ['yellow/400', 'Dummy shell'],
  'subject/shade': ['yellow/500', 'Dummy shell shadow side'],
  'subject/highlight': ['yellow/300', 'Dummy shell highlight'],
  'subject/joint': ['ink/800', 'Joints, hips, boots'],
  'subject/joint-highlight': ['slate/500', 'Highlights on dark joints'],
  'subject/marker': ['ink/900', 'Crash-test target quadrants'],
  'subject/scuff': ['orange/500', 'Damage scuffs (Hurt state)'],
  'subject/bandage': ['white', 'Bandage decal (Hurt state)'],
  'subject/flash': ['white', 'Hit-flash fill'],

  'rig/pivot': ['blue/500', 'Joint pivot markers (editor only)'],
  'rig/bone': ['blue/400', 'Bone lines (editor only)'],
  'rig/pivot-ring': ['white', 'Pivot marker ring'],

  'weapon/metal': ['slate/100', 'Blades and bright steel'],
  'weapon/metal-shade': ['slate/300', 'Steel shadow side'],
  'weapon/metal-dark': ['slate/600', 'Holes, axles, deep steel'],
  'weapon/frame': ['slate/500', 'Mounts and housings'],
  'weapon/paint': ['red/500', 'Safety-red painted parts'],
  'weapon/paint-shade': ['red/600', 'Painted parts shadow side'],
  'weapon/hazard-a': ['yellow/400', 'Hazard stripe light'],
  'weapon/hazard-b': ['ink/800', 'Hazard stripe dark'],
  'weapon/hitbox': ['red/400', 'Damage zone guide (editor only)'],
  'weapon/pivot': ['blue/500', 'Motion origin guide (editor only)'],
  'weapon/spark': ['yellow/300', 'Contact sparks'],
  'weapon/motion': ['white', 'Motion arcs and steel shine'],

  'ui/surface': ['white', 'Cards, pills, HUD panels'],
  'ui/surface-alt': ['slate/50', 'Documentation canvas'],
  'ui/surface-sunken': ['slate/100', 'Icon wells, inputs'],
  'ui/surface-locked': ['slate/200', 'Locked card'],
  'ui/surface-inverse': ['ink/800', 'Dark trays and toolbars'],
  'ui/outline': ['ink/900', 'UI outline'],
  'ui/text': ['ink/900', 'Primary text'],
  'ui/text-muted': ['slate/500', 'Secondary text'],
  'ui/text-inverse': ['white', 'Text on dark or saturated fills'],
  'ui/text-inverse-muted': ['slate/300', 'Secondary text on dark fills'],
  'ui/icon': ['ink/900', 'Default icon color'],
  'ui/silhouette': ['slate/400', 'Locked weapon silhouette'],
  'ui/primary': ['green/500', 'Start and upgrade actions'],
  'ui/primary-shade': ['green/600', 'Pressed primary'],
  'ui/accent': ['blue/500', 'Selection, unlock'],
  'ui/accent-soft': ['blue/300', 'Selected icon well'],
  'ui/coin': ['yellow/400', 'Coin face'],
  'ui/coin-shade': ['yellow/600', 'Coin rim'],
  'ui/danger': ['red/500', 'Destructive actions, timer warning'],
  'ui/warning': ['orange/400', 'Warnings'],
  'ui/disabled': ['slate/300', 'Disabled fill'],
  'ui/track': ['slate/200', 'Progress track, empty pips'],
  'ui/progress': ['red/400', 'Damage progress fill'],
  'ui/progress-complete': ['yellow/400', 'Damage goal reached'],

  'fx/outline': ['ink/900', 'Outline on floating text'],
  'fx/damage-normal': ['white', 'Floating damage: normal hit'],
  'fx/damage-heavy': ['yellow/400', 'Floating damage: heavy hit'],
  'fx/damage-crit': ['red/400', 'Floating damage: critical hit'],
  'fx/crit-burst': ['yellow/300', 'Critical starburst'],
  'fx/combo-1': ['yellow/400', 'Combo tier 1 (x2–x4)'],
  'fx/combo-2': ['orange/400', 'Combo tier 2 (x5–x9)'],
  'fx/combo-3': ['pink/500', 'Combo tier 3 (x10+)'],
  'fx/place-valid': ['green/400', 'Placement allowed'],
  'fx/place-invalid': ['red/400', 'Placement blocked'],
};

// [value, scopes]
var RDL_DIMENSIONS = {
  'space/2': [2, ['GAP']],
  'space/4': [4, ['GAP']],
  'space/6': [6, ['GAP']],
  'space/8': [8, ['GAP']],
  'space/10': [10, ['GAP']],
  'space/12': [12, ['GAP']],
  'space/16': [16, ['GAP']],
  'space/20': [20, ['GAP']],
  'space/24': [24, ['GAP']],
  'space/32': [32, ['GAP']],
  'space/48': [48, ['GAP']],
  'space/64': [64, ['GAP']],
  'radius/xs': [6, ['CORNER_RADIUS']],
  'radius/sm': [10, ['CORNER_RADIUS']],
  'radius/md': [16, ['CORNER_RADIUS']],
  'radius/lg': [24, ['CORNER_RADIUS']],
  'radius/pill': [999, ['CORNER_RADIUS']],
  'stroke/thin': [2, ['STROKE_FLOAT']],
  'stroke/outline': [4, ['STROKE_FLOAT']],
  'stroke/bold': [6, ['STROKE_FLOAT']],
};

// family: 'display' | 'body'
var RDL_TEXT_STYLES = {
  'Display/Hero': { family: 'display', weight: 'heavy', size: 120, line: 100, track: 1 },
  'Display/XL': { family: 'display', weight: 'heavy', size: 72, line: 100, track: 1 },
  'Display/L': { family: 'display', weight: 'heavy', size: 48, line: 100, track: 1 },
  'Display/M': { family: 'display', weight: 'heavy', size: 36, line: 100, track: 2 },
  'Display/S': { family: 'display', weight: 'heavy', size: 26, line: 110, track: 2 },
  'Label/L': { family: 'body', weight: 'black', size: 20, line: 120, track: 4, upper: true },
  'Label/M': { family: 'body', weight: 'extrabold', size: 16, line: 120, track: 4, upper: true },
  'Label/S': { family: 'body', weight: 'extrabold', size: 12, line: 120, track: 6, upper: true },
  'Body/M': { family: 'body', weight: 'semibold', size: 16, line: 140, track: 0 },
  'Body/S': { family: 'body', weight: 'semibold', size: 13, line: 140, track: 0 },
};

if (typeof module !== 'undefined') module.exports = { RDL_PRIMITIVES: RDL_PRIMITIVES, RDL_COLORS: RDL_COLORS, RDL_DIMENSIONS: RDL_DIMENSIONS, RDL_TEXT_STYLES: RDL_TEXT_STYLES };
